###
# @name Authentifizierung VB
POST https://{{.stage}}.auth.dvag/auth/realms/zob/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=app-web-vp-digital&
grant_type=password&
username={{.vb}}&
password={{.password}}

> {%
    client.global.set("token", response.body.access_token)
%}

###
# @name Produktkonfiguration
POST {{.baseUrl}}/api/v3/tarifrechner/produktkonfigurationen
Authorization: Bearer {{.token}}
Content-Type: application/json

{
  "tarifrechnerModus": {
    "modus": "PRIVATKUNDEN_BEDARFSBERATUNG",
    "mandant": "DVAG",
    "haushaltsId": "{{.haushaltsId}}"
  }
}

> {%
    const jsonData = response.body
    //
    client.global.set("produktId", jsonData.produktkonfigurationen[0].id)
    client.global.set("kundenNummer", jsonData.produktkonfigurationen[0].moeglicheNeukunden.kunden[0].kundennummer)
%}

###
# @name Tarifrechner anlegen
POST {{.baseUrl}}/api/v3/tarifrechner
Authorization: Bearer {{.token}}
Content-Type: application/json

{
"tarifrechnerModus": {
"modus": "PRIVATKUNDEN_BEDARFSBERATUNG",
"mandant": "DVAG",
"haushaltsId": "{{.haushaltsId}}"
},
"produktKonfigurationId": "Kontoeroeffnung",
"kundennummern": [
    "99152160"
]
}

> {%
    var jsonData = response.body
    client.global.set("tarifrechnerId", jsonData.id)
%}

###
# @name Tarifrechner entfernen
DELETE {{.baseUrl}}/api/v3/tarifrechner/{{.tarifrechnerId}}
Authorization: Bearer {{.token}}
