### 
# @name Test Assert Failure
> {%
console.log("Testing assert failure...");
client.assert(function() {
    return false; // This should fail
}, "This assertion should fail", 400);
console.log("This should never be logged");
%}

POST https://httpbin.org/post
Content-Type: application/json

{
  "test": "should not execute"
}

###