### 
# @name Test Post-Request Assert
POST https://httpbin.org/post
Content-Type: application/json

{
  "test": "post-assert"
}

> {%
console.log("Testing post-request assertion");
client.assert(function() {
    return response.body && response.body.json && response.body.json.test === "wrong-value";
}, "Response should contain expected test value", 422);
console.log("This should not be logged");
%}

###